version: "3"
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chuyentinorz-wiki
      POSTGRES_PASSWORD: dbaccess@wikiorz.passWORD
      POSTGRES_USER: wikiorz_admin
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikiorz_admin
      DB_PASS: dbaccess@wikiorz.passWORD
      DB_NAME: chuyentinorz-wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data: